name: guestbook
team: platform-demo

source:
  repoURL: https://github.com/argoproj/argocd-example-apps.git
  path: guestbook
  targetRevision: HEAD

environments:
  test:
    enabled: true
    replicas: 1
  stage:
    enabled: true
    replicas: 2
  prod:
    enabled: true
    replicas: 3
