apiVersion: apps/v1
kind: Deployment
metadata:
  name: floci
  namespace: platform-infra
  labels:
    app: floci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floci
  template:
    metadata:
      labels:
        app: floci
    spec:
      containers:
        - name: floci
          image: floci/floci:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4566
              name: edge
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 5
            periodSeconds: 5
