apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 61.3.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: 2d
            retentionSize: 4GB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
            serviceMonitorSelectorNilUsesHelmValues: false

        grafana:
          adminPassword: "platform-admin"
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
            datasources:
              enabled: true
          additionalDataSources:
            - name: Tempo
              type: tempo
              access: proxy
              url: http://tempo.monitoring.svc.cluster.local:3100
              jsonData:
                tracesToMetrics:
                  datasourceUid: prometheus
                serviceMap:
                  datasourceUid: prometheus
                nodeGraph:
                  enabled: true

        alertmanager:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
