apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-alpha
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/<YOUR_USERNAME>/Flagship-Platform.git
    targetRevision: main
    path: platform-gitops/tenants/team-alpha
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-team-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
