apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - git:
        repoURL: https://github.com/barbaria888/FrugalZeus.git
        revision: main
        directories:
          - path: platform-gitops/tenants/*
          - path: platform-gitops/tenants/base
            exclude: true
  template:
    metadata:
      name: 'tenant-{{path.basename}}'
      namespace: argocd
      labels:
        platform.io/tenant: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/barbaria888/FrugalZeus.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'tenant-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
