apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.28.1"
    helm:
      values: |
        server:
          dev:
            enabled: false
          ha:
            enabled: false
          dataStorage:
            enabled: true
            size: 5Gi
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          ui:
            enabled: true
        injector:
          enabled: false          # ESO is used instead of the sidecar injector
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
