apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: team-alpha-secrets
  namespace: tenant-team-alpha
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: team-alpha-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: tenants/team-alpha/app
        property: DB_PASSWORD
    - secretKey: API_KEY
      remoteRef:
        key: tenants/team-alpha/app
        property: API_KEY
