apiVersion: v1
kind: Service
metadata:
  name: team-alpha-svc
  namespace: tenant-team-alpha
  labels:
    app: team-alpha-svc
    platform.io/tenant: "true"
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
    - name: metrics
      port: 9464
      targetPort: 9464
  selector:
    app: team-alpha-svc
