site_name: FrugalZeus⚜️
site_description: Cloud-Native Engineering Platform 
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Onboard a Team: onboarding.md
  - Observability: observability.md
  - Cost Attribution: finops.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
